import Head from "next/head";
import { useEffect } from "react";
import AOS from 'aos';
import NavBar from "@/components/organism/NavBar";
import MainBanner from "@/components/organism/MainBanner";
import TransactionStep from "@/components/organism/TransactionStep";
import FeaturedGame from "@/components/organism/FeaturedGame";
import Reached from "@/components/organism/Reached";
import Story from "@/components/organism/Story";
import Footer from "@/components/organism/Footer";

export default function Home() {

  useEffect(() => {
    AOS.init();
  }, [])

  return (
    <>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar />
        <MainBanner />
        <TransactionStep />
        <FeaturedGame />
        <Reached />
        <Story />
        <Footer />
      </>
    </>
  );
}
